<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ReviewComment } from '../lib/aiReviewTypes';
import { language, t } from '../lib/i18n';
import { renderReviewComment } from '../lib/markdownDocument';

const props = defineProps<{ comment: ReviewComment; createdAt?: number; lineText?: string; contextPath?: string; canNavigate?: boolean; showAnchor?: boolean; outdated?: boolean; focused?: boolean; resolved?: boolean; canResolve?: boolean }>();
const emit = defineEmits<{ markComment: [id: string, status: 'resolved' | 'open']; navigate: [] }>();
const collapsed = ref(!!props.resolved);
const preview = computed(() => props.comment.body.replace(/```[^\n]*\n?/g, '').replace(/[`*_#>]/g, '').replace(/\s+/g, ' ').trim());
watch(() => props.resolved, value => { collapsed.value = !!value; });
watch(() => props.focused, value => { if (value) collapsed.value = false; }, { immediate: true });
</script>
<template>
  <div class="diff-review-comment" :class="{ 'is-focused': focused, 'is-collapsed': resolved && collapsed }" :data-comment-id="comment.id">
    <div v-if="resolved && collapsed" class="diff-review-comment-collapsed"><span v-if="contextPath" class="diff-review-context-path" :title="contextPath"><i class="bi bi-file-code" aria-hidden="true"></i>{{ contextPath }}</span><button type="button" class="diff-review-comment-preview" :aria-label="language === 'zh-CN' ? '展开已解决评论' : 'Expand resolved comment'" @click="collapsed = false"><i class="bi bi-chevron-right" aria-hidden="true"></i><strong>Ming AI</strong><span>{{ preview || (language === 'zh-CN' ? '已解决的评论' : 'Resolved comment') }}</span></button><span class="diff-review-resolved-label">{{ language === 'zh-CN' ? '已解决' : 'Resolved' }}</span><button v-if="canNavigate" type="button" class="diff-review-navigate" :title="language === 'zh-CN' ? '在文件中查看' : 'View in files'" :aria-label="language === 'zh-CN' ? '在文件中查看' : 'View in files'" @click="emit('navigate')"><i class="bi bi-arrow-right" aria-hidden="true"></i></button></div>
    <template v-else><header :class="{ 'has-time': createdAt }"><span class="diff-review-avatar"><i class="bi bi-robot" aria-hidden="true"></i></span><strong>Ming AI</strong><span>{{ t('commented') }}</span><span v-if="outdated" class="diff-comment-outdated">{{ t('Out of date') }}</span><span v-if="resolved" class="review-resolution-label">{{ language === 'zh-CN' ? '已解决' : 'Resolved' }}</span><span v-if="comment.severity" class="review-severity" :class="`is-${comment.severity}`">{{ t(({ high: 'High', medium: 'Medium', low: 'Low' })[comment.severity]) }}</span><time v-if="createdAt" :datetime="new Date(createdAt).toISOString()">{{ new Date(createdAt).toLocaleString(language) }}</time><button v-if="resolved" type="button" class="diff-review-collapse" @click="collapsed = true">{{ language === 'zh-CN' ? '收起' : 'Collapse' }}</button></header>
    <div class="diff-review-comment-body"><div v-if="contextPath" class="diff-review-context-expanded"><span><i class="bi bi-file-code" aria-hidden="true"></i>{{ contextPath }}</span><button v-if="canNavigate" type="button" @click="emit('navigate')">{{ language === 'zh-CN' ? '在文件中查看' : 'View in files' }} <i class="bi bi-arrow-right" aria-hidden="true"></i></button></div><div v-if="showAnchor" class="diff-review-anchor"><code>{{ comment.side === 'LEFT' ? '−' : '+' }}{{ comment.lineNumber }}</code><code v-if="lineText">{{ lineText }}</code></div><div class="diff-review-comment-markdown" v-html="renderReviewComment(comment.body)"></div><div v-if="comment.suggestion" class="diff-review-suggestion"><strong>{{ t('Suggested change') }}</strong><pre><code>{{ comment.suggestion }}</code></pre></div><div v-if="canResolve" class="diff-review-comment-actions"><span v-if="!resolved">{{ language === 'zh-CN' ? '未解决' : 'Open' }}</span><button type="button" class="button-outline" @click="emit('markComment', comment.id, resolved ? 'open' : 'resolved')">{{ resolved ? (language === 'zh-CN' ? '重新打开' : 'Reopen') : (language === 'zh-CN' ? '标记已解决' : 'Resolve') }}</button></div></div></template>
  </div>
</template>
